version: '3.7'

services:
  api:
    build: .
    image: geocoder-api:${CARTOROUTE_VERSION:-latest}
    ports:
      - "8081:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - .:/srv/app
      - ./docker/production.rb:/srv/app/config/environments/production.rb
      - ./docker/production.rb:/srv/app/config/environments/development.rb
      - ./poly:/srv/app/poly
    environment:
      REDIS_HOST: redis-cache
      APP_ENV: production # Swith to "development" for more traces
      HERE_APIKEY: ${HERE_APIKEY}
    links:
      - redis-cache
    command: bundle exec puma -v -p 80 --pidfile 'server.pid'
    restart: unless-stopped

  redis-cache:
    image: redis:${REDIS_VERSION:-7-alpine}
    hostname: redis-cache
    command: redis-server --save ""
    volumes:
      - ./docker/redis-cache:/data
    restart: unless-stopped
