version: '3.7'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ..:/srv/app
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./production.rb:/srv/app/config/environments/development.rb
      - ../poly:/srv/app/poly
    environment:
      REDIS_COUNT_HOST: redis-count
      REDIS_HOST: redis-cache
      APP_ENV: production # Swith to "development" for more traces
    links:
      - redis-cache
      - redis-count
      - addok-fr
      - addok-lu
    command: bundle exec puma -v -p 80 --pidfile 'server.pid'
    restart: unless-stopped

  redis-cache:
    image: redis:${REDIS_VERSION:-7-alpine}
    hostname: redis-cache
    command: redis-server --save ""
    volumes:
      - ./redis:/data
    restart: unless-stopped

  redis-count:
    image: redis:${REDIS_VERSION:-7-alpine}
    hostname: redis-count
    command: redis-server --appendonly yes
    volumes:
      - ./redis-count:/data
    restart: unless-stopped

  # France
  addok-fr:
    build:
      context: addok
    volumes:
      - ./addok/addok-fr.conf:/etc/addok/addok.conf
      - ./addresses-fr:/addresses
    links:
      - redis-addok-fr
    environment:
      ADDOK_HOST: "redis-addok-fr"
      ADDOK_ATTRIBUTION: "BAN"
      ADDOK_LICENCE: "ODbL"
    command: gunicorn --bind 0.0.0.0:7878 --timeout 7200 --workers 8 addok.http.wsgi

    restart: unless-stopped

  redis-addok-fr:
    image: redis:${REDIS_VERSION:-7-alpine}
    command: redis-server --save ""
    volumes:
      - ./data:/data
    restart: unless-stopped

  # Luxemburg
  addok-lu:
    build:
      context: addok
    volumes:
      - ./addok/addok-lu.conf:/etc/addok/addok.conf
      - ./addresses-lu:/addresses
    links:
      - redis-addok-lu
    environment:
      ADDOK_HOST: "redis-addok-lu"
      ADDOK_ATTRIBUTION: "Grand-Duché of Luxembourg"
      ADDOK_LICENCE: "CC0"
    command: gunicorn --bind 0.0.0.0:7878 --timeout 7200 --workers 8 addok.http.wsgi
    restart: unless-stopped

  redis-addok-lu:
    image: redis:${REDIS_VERSION:-7-alpine}
    command: redis-server --save ""
    volumes:
      - ./data:/data
    restart: unless-stopped
